# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "Saurav"
languageCode = "en-us"
baseURL = "https://assam.netlify.app/"
copyright = "Â©ASSAA {2020}"

# Add your Disqus shortname here.
  disqusShortname = "https-assaa-netlify-app-1"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/ConfusedPostdoc"
  github = "https://github.com/Saurav12das"
  email = "mailto:<saurav12das@gmail.com>"
  facebook = "https://facebook.com/<saurav12das>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "Email", "Facebook"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "post"
  name = "post"
  title = "Post"
  url = "/post"

  
##Site Features
highlight = true
highlight_languages = ["r"]  # Add support for highlighting additional languages
highlight_style = "tomorrow"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/
show_related = {docs = true, page = true, post = true, project = true, publication = true, talk = true}
netlify_cms = true
